version: '3.4'

services:
  mongo:
    image: mongo:5.0.6
    ports:
      - "27017:27017"
    restart: always
    enviroment:
        MONGO_INITDB_ROOT_USERNAME: '${MONGO_INITDB_ROOT_USERNAME}'
        MONGO_INITDB_ROOT_PASSWORD: '${MONGO_INITDB_ROOT_PASSWORD}'